format = "$username$shell$directory$env_var\n$character"

[aws]
disabled = true

[character]
success_symbol = "[ᐅ](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time = 5_000

[directory]
style = "italic purple"

[env_var.AWS_PROFILE]
format = "[󰸏 ](bold yellow)[$env_value]($style)"
style = "cyan"

[python]
disabled = true
symbol = " "

[shell]
disabled = false
style = "cyan"
bash_indicator = ""
fish_indicator = " "
nu_indicator = ""
zsh_indicator = "󰰶"

[terraform]
disabled = true
format = "[$symbol$version]($style) "
symbol = "󱁢 "

[username]
format = "[$user]($style)[ ](purple)"
