format = "$shell$directory$env_var\n$character"

[aws]
disabled = true

[character]
success_symbol = "[á…](bold green)"
error_symbol = "[âœ—](bold red)"

[cmd_duration]
min_time = 5_000

[directory]
style = "italic purple"

[env_var.AWS_PROFILE]
format = "[$env_value]($style)"
style = "bold cyan"

[python]
disabled = true

[shell]
disabled = false
bash_indicator = "â„¬"
# fish_indicator = "Æ’"
fish_indicator = "ğŸ "
nu_indicator = "â„•"
zsh_indicator = "â„¤"

[terraform]
disabled = true
# symbol = "ï­¨ " # looks great outside vterm
symbol = "ïƒ "

[username]
format = "[$user]($style)[ï‡º](purple)"
