format = "$directory\n$character"

[aws]
disabled = true
format = ' [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[character]
success_symbol = "[·êÖ](bold green)"
error_symbol = "[‚úó](bold red)"

[cmd_duration]
format = " [$duration]($style)"
min_time = 5_000

[directory]
read_only = " Ô†Ω"
style =  "italic purple dimmed"

[docker_context]
format = " [$symbol$context]($style)"

[env_var.AWS_PROFILE]
format = " [$symbol $env_value]($style)"
style = "bold cyan"
symbol = "üåß "

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style)"
symbol = "Ôêò "

[golang]
format = " [$symbol($version )]($style)"
symbol = "Óú§ "
version_format = "${raw}"

[java]
format = " [${symbol}(${version} )]($style)"
version_format = "${raw}"

[nim]
format = " [$symbol($version )]($style)"
version_format = "${raw}"

[nodejs]
format = " [$symbol($version )]($style)"
version_format = "${raw}"

[package]
format = " [$symbol$version]($style)"
version_format = "${raw}"

[python]
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "Ô†ü "
version_format = "${raw}"

[rust]
format = " [$symbol($version )]($style)"
version_format = "${raw}"

[terraform]
format = " [$symbol$version]($style)"
# symbol = "Ô≠® " # looks great outside vterm
symbol = "ÔûÉ "
version_format = "${raw}"

[username]
format = "[$user]($style)[Ôá∫](purple) "
